name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Enable write permission for checks API
permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build  # Only run if build succeeds
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - run: ./gradlew test || echo "::error ::Some tests failed"
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/test-results/test/

      - name: Publish test summary
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
