name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permissions to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build the project
      run: ./gradlew build

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: build/test-results/test/

    - name: Publish test summary
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
